---
# tasks file for app
- name: Extract repo name from URL
  ansible.builtin.set_fact:
    repository_name: "{{ repository_url.split('/')[-1].split('.')[0] }}"
    user_dir: "/home/{{ ansible_user }}"

- name: Ensure directory is empty
  ansible.builtin.file:
    path: "{{ user_dir }}/{{ repository_name }}"
    state: absent

- name: Fetch app files
  ansible.builtin.git:
    repo: "{{ repository_url }}"
    dest: "{{ user_dir }}/{{ repository_name }}"
    force: yes
    
- name: Install npm dependencies & build app
  ansible.builtin.shell: |
    npm install
    npm run build
  args:
    executable: /bin/bash
    chdir: "{{ user_dir }}/{{ repository_name }}/app"
  changed_when: true

- name: Create service unit
  ansible.builtin.template:
    src: templates/nodejs-server-service.j2
    dest: /etc/systemd/system/nodejs-server.service
    owner: azureuser
    group: azureuser
    mode: "0644"
  vars:
    working_directory: "{{ user_dir }}/{{ repository_name }}/app"

- name: Reload daemon and start new service
  ansible.builtin.systemd:
    name: nodejs-server.service
    state: started
    enabled: true
    daemon_reload: true
    