---
# tasks file for app
- name: Extract repo name from URL
  ansible.builtin.set_fact:
    repository_name: "{{ repository_url.split('/')[-1].split('.')[0] }}"

- name: Create web directory
  ansible.builtin.file:
    path: "{{ ansible_facts.user_dir }}/{{ repository_name }}/hello-world-app"
    state: directory
    mode: "0755"
    ownder: azureuser
    group: azureuser

- name: Fetch app files
  ansible.builtin.git:
    repo: "{{ repository_url }}"
    dest: "{{ ansible_facts.user_dir }}/{{ repository_name }}"

- name: Install npm dependencies & build app
  ansible.builtin.shell: |
    npm Install
    npm run build
  args:
    executable: /bin/bash
    chdir: "{{ ansible_facts.user_dir }}/{{ repository_name }}/hello-world-app"
  changed_when: true

- name: Create service unit
  ansible.builtin.template:
    src: templates/nodejs-server-service.j2
    dest: /etc/systemd/system/nodejs-server-service
    owner: azureuser
    group: azureuser
    mode: "0644"
  vars:
    working_directory: "{{ ansible_facts.user_dir }}/{{ repository_name }}/hello-world-app"

- name: Reload daemon and start new service
  ansible.builtin.systemd:
    name: nodejs-server.service
    state: started
    enabled: true
    daemon_reload: true
    